// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckUpdate():Promise<string>;

export function ClearShaderCache():Promise<string>;

export function DisableCState():Promise<boolean>;

export function DisableDefender():Promise<boolean>;

export function DisableDriverUpdates():Promise<boolean>;

export function DisableFastStartup():Promise<boolean>;

export function DisableFullscreenOptimization():Promise<boolean>;

export function DisableHibernate():Promise<boolean>;

export function DisableMemoryCompression():Promise<boolean>;

export function DisableMemoryIntegrity():Promise<boolean>;

export function DisableMpo():Promise<boolean>;

export function DisablePauseUpdates():Promise<boolean>;

export function DisablePhotoViewer():Promise<boolean>;

export function DisableSuperfetch():Promise<boolean>;

export function DisableUac():Promise<boolean>;

export function DisableUltimatePerformance():Promise<boolean>;

export function DisableVbs():Promise<boolean>;

export function DisableVisibility():Promise<boolean>;

export function DisableWindowedOptimization():Promise<boolean>;

export function EnableCState():Promise<boolean>;

export function EnableDefender():Promise<boolean>;

export function EnableDriverUpdates():Promise<boolean>;

export function EnableFastStartup():Promise<boolean>;

export function EnableFullscreenOptimization():Promise<boolean>;

export function EnableHibernate():Promise<boolean>;

export function EnableMemoryCompression():Promise<boolean>;

export function EnableMemoryIntegrity():Promise<boolean>;

export function EnableMpo():Promise<boolean>;

export function EnablePauseUpdates():Promise<boolean>;

export function EnablePhotoViewer():Promise<boolean>;

export function EnableSuperfetch():Promise<boolean>;

export function EnableUac():Promise<boolean>;

export function EnableUltimatePerformance():Promise<boolean>;

export function EnableVbs():Promise<boolean>;

export function EnableVisibility():Promise<boolean>;

export function EnableWindowedOptimization():Promise<boolean>;

export function GetCStateStatus():Promise<boolean>;

export function GetCurrentVersion():Promise<string>;

export function GetDefenderStatus():Promise<boolean>;

export function GetDriverUpdatesStatus():Promise<boolean>;

export function GetEdgeSwipeStatus():Promise<boolean>;

export function GetExplorerGalleryStatus():Promise<boolean>;

export function GetExplorerHomeStatus():Promise<boolean>;

export function GetFastStartupStatus():Promise<boolean>;

export function GetFullscreenOptimizationStatus():Promise<boolean>;

export function GetHibernateStatus():Promise<boolean>;

export function GetLegacyBalloonStatus():Promise<boolean>;

export function GetMemoryCompressionStatus():Promise<boolean>;

export function GetMemoryIntegrityStatus():Promise<boolean>;

export function GetMpoStatus():Promise<boolean>;

export function GetNewContextMenuStatus():Promise<boolean>;

export function GetNotificationStatus():Promise<string>;

export function GetPauseUpdatesStatus():Promise<boolean>;

export function GetPhotoViewerStatus():Promise<boolean>;

export function GetProxyInfo():Promise<string>;

export function GetRemoveShieldStatus():Promise<boolean>;

export function GetRemoveShortcutArrowStatus():Promise<boolean>;

export function GetRemoveShortcutTextStatus():Promise<boolean>;

export function GetSuperfetchStatus():Promise<boolean>;

export function GetSystemInfo():Promise<string>;

export function GetUacStatus():Promise<boolean>;

export function GetUltimatePerformanceStatus():Promise<boolean>;

export function GetUpdateChannel():Promise<string>;

export function GetVbsStatus():Promise<boolean>;

export function GetVisibilityStatus():Promise<boolean>;

export function GetWebView2Version():Promise<string>;

export function GetWindowedOptimizationStatus():Promise<boolean>;

export function InstallWebView2():Promise<string>;

export function RebootSystem():Promise<boolean>;

export function RebootToBios():Promise<boolean>;

export function RestartExplorer():Promise<string>;

export function SetEdgeSwipe(arg1:boolean):Promise<boolean>;

export function SetExplorerGallery(arg1:boolean):Promise<boolean>;

export function SetExplorerHome(arg1:boolean):Promise<boolean>;

export function SetLegacyBalloon(arg1:boolean):Promise<boolean>;

export function SetNewContextMenu(arg1:boolean):Promise<boolean>;

export function SetNotificationMode(arg1:string):Promise<boolean>;

export function SetRemoveShield(arg1:boolean):Promise<boolean>;

export function SetRemoveShortcutArrow(arg1:boolean):Promise<boolean>;

export function SetRemoveShortcutText(arg1:boolean):Promise<boolean>;

export function SetSafeBoot(arg1:string):Promise<boolean>;

export function SetUpdateChannel(arg1:string):Promise<boolean>;

export function UninstallEdge():Promise<string>;

export function UpdateCertificates():Promise<string>;

export function UpdateKGL():Promise<string>;
