// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function DisableCState() {
  return window['go']['main']['App']['DisableCState']();
}

export function DisableDefender() {
  return window['go']['main']['App']['DisableDefender']();
}

export function DisableDriverUpdates() {
  return window['go']['main']['App']['DisableDriverUpdates']();
}

export function DisableFastStartup() {
  return window['go']['main']['App']['DisableFastStartup']();
}

export function DisableFullscreenOptimization() {
  return window['go']['main']['App']['DisableFullscreenOptimization']();
}

export function DisableHibernate() {
  return window['go']['main']['App']['DisableHibernate']();
}

export function DisableMemoryCompression() {
  return window['go']['main']['App']['DisableMemoryCompression']();
}

export function DisableMemoryIntegrity() {
  return window['go']['main']['App']['DisableMemoryIntegrity']();
}

export function DisableMpo() {
  return window['go']['main']['App']['DisableMpo']();
}

export function DisablePauseUpdates() {
  return window['go']['main']['App']['DisablePauseUpdates']();
}

export function DisablePhotoViewer() {
  return window['go']['main']['App']['DisablePhotoViewer']();
}

export function DisableSuperfetch() {
  return window['go']['main']['App']['DisableSuperfetch']();
}

export function DisableUac() {
  return window['go']['main']['App']['DisableUac']();
}

export function DisableUltimatePerformance() {
  return window['go']['main']['App']['DisableUltimatePerformance']();
}

export function DisableVbs() {
  return window['go']['main']['App']['DisableVbs']();
}

export function DisableVisibility() {
  return window['go']['main']['App']['DisableVisibility']();
}

export function DisableWindowedOptimization() {
  return window['go']['main']['App']['DisableWindowedOptimization']();
}

export function EnableCState() {
  return window['go']['main']['App']['EnableCState']();
}

export function EnableDefender() {
  return window['go']['main']['App']['EnableDefender']();
}

export function EnableDriverUpdates() {
  return window['go']['main']['App']['EnableDriverUpdates']();
}

export function EnableFastStartup() {
  return window['go']['main']['App']['EnableFastStartup']();
}

export function EnableFullscreenOptimization() {
  return window['go']['main']['App']['EnableFullscreenOptimization']();
}

export function EnableHibernate() {
  return window['go']['main']['App']['EnableHibernate']();
}

export function EnableMemoryCompression() {
  return window['go']['main']['App']['EnableMemoryCompression']();
}

export function EnableMemoryIntegrity() {
  return window['go']['main']['App']['EnableMemoryIntegrity']();
}

export function EnableMpo() {
  return window['go']['main']['App']['EnableMpo']();
}

export function EnablePauseUpdates() {
  return window['go']['main']['App']['EnablePauseUpdates']();
}

export function EnablePhotoViewer() {
  return window['go']['main']['App']['EnablePhotoViewer']();
}

export function EnableSuperfetch() {
  return window['go']['main']['App']['EnableSuperfetch']();
}

export function EnableUac() {
  return window['go']['main']['App']['EnableUac']();
}

export function EnableUltimatePerformance() {
  return window['go']['main']['App']['EnableUltimatePerformance']();
}

export function EnableVbs() {
  return window['go']['main']['App']['EnableVbs']();
}

export function EnableVisibility() {
  return window['go']['main']['App']['EnableVisibility']();
}

export function EnableWindowedOptimization() {
  return window['go']['main']['App']['EnableWindowedOptimization']();
}

export function GetCStateStatus() {
  return window['go']['main']['App']['GetCStateStatus']();
}

export function GetCurrentVersion() {
  return window['go']['main']['App']['GetCurrentVersion']();
}

export function GetDefenderStatus() {
  return window['go']['main']['App']['GetDefenderStatus']();
}

export function GetDriverUpdatesStatus() {
  return window['go']['main']['App']['GetDriverUpdatesStatus']();
}

export function GetEdgeSwipeStatus() {
  return window['go']['main']['App']['GetEdgeSwipeStatus']();
}

export function GetExplorerGalleryStatus() {
  return window['go']['main']['App']['GetExplorerGalleryStatus']();
}

export function GetExplorerHomeStatus() {
  return window['go']['main']['App']['GetExplorerHomeStatus']();
}

export function GetFastStartupStatus() {
  return window['go']['main']['App']['GetFastStartupStatus']();
}

export function GetFullscreenOptimizationStatus() {
  return window['go']['main']['App']['GetFullscreenOptimizationStatus']();
}

export function GetHibernateStatus() {
  return window['go']['main']['App']['GetHibernateStatus']();
}

export function GetLegacyBalloonStatus() {
  return window['go']['main']['App']['GetLegacyBalloonStatus']();
}

export function GetMemoryCompressionStatus() {
  return window['go']['main']['App']['GetMemoryCompressionStatus']();
}

export function GetMemoryIntegrityStatus() {
  return window['go']['main']['App']['GetMemoryIntegrityStatus']();
}

export function GetMpoStatus() {
  return window['go']['main']['App']['GetMpoStatus']();
}

export function GetNewContextMenuStatus() {
  return window['go']['main']['App']['GetNewContextMenuStatus']();
}

export function GetNotificationStatus() {
  return window['go']['main']['App']['GetNotificationStatus']();
}

export function GetPauseUpdatesStatus() {
  return window['go']['main']['App']['GetPauseUpdatesStatus']();
}

export function GetPhotoViewerStatus() {
  return window['go']['main']['App']['GetPhotoViewerStatus']();
}

export function GetRemoveShieldStatus() {
  return window['go']['main']['App']['GetRemoveShieldStatus']();
}

export function GetRemoveShortcutArrowStatus() {
  return window['go']['main']['App']['GetRemoveShortcutArrowStatus']();
}

export function GetRemoveShortcutTextStatus() {
  return window['go']['main']['App']['GetRemoveShortcutTextStatus']();
}

export function GetSuperfetchStatus() {
  return window['go']['main']['App']['GetSuperfetchStatus']();
}

export function GetUacStatus() {
  return window['go']['main']['App']['GetUacStatus']();
}

export function GetUltimatePerformanceStatus() {
  return window['go']['main']['App']['GetUltimatePerformanceStatus']();
}

export function GetVbsStatus() {
  return window['go']['main']['App']['GetVbsStatus']();
}

export function GetVisibilityStatus() {
  return window['go']['main']['App']['GetVisibilityStatus']();
}

export function GetWebView2Version() {
  return window['go']['main']['App']['GetWebView2Version']();
}

export function GetWindowedOptimizationStatus() {
  return window['go']['main']['App']['GetWindowedOptimizationStatus']();
}

export function InstallWebView2() {
  return window['go']['main']['App']['InstallWebView2']();
}

export function RestartExplorer() {
  return window['go']['main']['App']['RestartExplorer']();
}

export function SetEdgeSwipe(arg1) {
  return window['go']['main']['App']['SetEdgeSwipe'](arg1);
}

export function SetExplorerGallery(arg1) {
  return window['go']['main']['App']['SetExplorerGallery'](arg1);
}

export function SetExplorerHome(arg1) {
  return window['go']['main']['App']['SetExplorerHome'](arg1);
}

export function SetLegacyBalloon(arg1) {
  return window['go']['main']['App']['SetLegacyBalloon'](arg1);
}

export function SetNewContextMenu(arg1) {
  return window['go']['main']['App']['SetNewContextMenu'](arg1);
}

export function SetNotificationMode(arg1) {
  return window['go']['main']['App']['SetNotificationMode'](arg1);
}

export function SetRemoveShield(arg1) {
  return window['go']['main']['App']['SetRemoveShield'](arg1);
}

export function SetRemoveShortcutArrow(arg1) {
  return window['go']['main']['App']['SetRemoveShortcutArrow'](arg1);
}

export function SetRemoveShortcutText(arg1) {
  return window['go']['main']['App']['SetRemoveShortcutText'](arg1);
}

export function ToggleDriverUpdates(arg1) {
  return window['go']['main']['App']['ToggleDriverUpdates'](arg1);
}

export function ToggleHibernate(arg1) {
  return window['go']['main']['App']['ToggleHibernate'](arg1);
}

export function ToggleMemCompress(arg1) {
  return window['go']['main']['App']['ToggleMemCompress'](arg1);
}

export function ToggleNotification(arg1) {
  return window['go']['main']['App']['ToggleNotification'](arg1);
}

export function TogglePowerPlan(arg1) {
  return window['go']['main']['App']['TogglePowerPlan'](arg1);
}

export function ToggleSuperfetch(arg1) {
  return window['go']['main']['App']['ToggleSuperfetch'](arg1);
}

export function UninstallEdge() {
  return window['go']['main']['App']['UninstallEdge']();
}

export function UpdateCertificates() {
  return window['go']['main']['App']['UpdateCertificates']();
}

export function UpdateKGL() {
  return window['go']['main']['App']['UpdateKGL']();
}
